---
- name: Ensure apt cache is up to date
  apt: update_cache=yes

- name: Install Imagemagick
  apt: name={{ item }}
  sudo: yes
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev


- name: Fix locales
  sudo: yes
  shell: locale-gen en_CA en_CA.UTF-8

- name: Fix locales2
  sudo: yes
  shell: dpkg-reconfigure locales