---
- name: Ensure apt cache is up to date
  apt: update_cache=yes

- name: Install Imagemagick
  apt: name={{ item }}
  sudo: yes
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev