- name: Add Postgis repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt trusty-pgdg main' state=present

- name: Add Postgis repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: Install Postgres, Postgis and python-psycopg2
  apt: name={{ item }} update_cache=yes
  with_items:
    - postgresql-9.3-postgis-2.1 
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: Copy pg_hba conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/
  notify: restart psql

- name: Create user
  user: name={{ db_user_name }}

- name: Create Postgres user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user_name }} password={{ db_pword }} role_attr_flags=CREATEDB
