
- name: Install Ruby dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - git-core curl 
    - zlib1g-dev 
    - build-essential 
    - libssl-dev 
    - libreadline-dev 
    - libyaml-dev 
    - libsqlite3-dev 
    - sqlite3 
    - libxml2-dev 
    - libxslt1-dev 
    - libcurl4-openssl-dev 
    - python-software-properties 
    - libffi-dev

- name: Download ruby
  get_url: url={{ ruby_url }} dest=/home/ubuntu/ruby-{{ ruby_version }}.tar

- name: Extract ruby
  command: tar -zxf /home/ubuntu/ruby-{{ ruby_version}}.tar creates=/home/ubuntu/ruby-{{ ruby_version }}

- name: Make, configure, and install ruby
  command: "{{ item }} chdir=/home/ubuntu/ruby-{{ ruby_version }}"
  with_items:
    - ./configure
    - make
    - sudo make install

- name: Install Ruby on Rails
  gem: name=rails version=4.2.1 state=present